/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Painel4s9fk27qzRouteImport } from './routes/painel-4s-9fk27qz'
import { Route as IndexRouteImport } from './routes/index'

const Painel4s9fk27qzRoute = Painel4s9fk27qzRouteImport.update({
  id: '/painel-4s-9fk27qz',
  path: '/painel-4s-9fk27qz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel-4s-9fk27qz': typeof Painel4s9fk27qzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel-4s-9fk27qz': typeof Painel4s9fk27qzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel-4s-9fk27qz': typeof Painel4s9fk27qzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel-4s-9fk27qz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel-4s-9fk27qz'
  id: '__root__' | '/' | '/painel-4s-9fk27qz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Painel4s9fk27qzRoute: typeof Painel4s9fk27qzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel-4s-9fk27qz': {
      id: '/painel-4s-9fk27qz'
      path: '/painel-4s-9fk27qz'
      fullPath: '/painel-4s-9fk27qz'
      preLoaderRoute: typeof Painel4s9fk27qzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Painel4s9fk27qzRoute: Painel4s9fk27qzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
